config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  direct :rails_public_blob do |blob|
    # Preserve the behaviour of `rails_blob_url` inside these environments
    # where S3 or the CDN might not be configured
    if Rails.env.development? || Rails.env.test?
      route = 
        # ActiveStorage::VariantWithRecord was introduced in Rails 6.1
        # Remove the second check if you're using an older version
        if blob.is_a?(ActiveStorage::Variant) || blob.is_a?(ActiveStorage::VariantWithRecord)
          :rails_representation
        else
         :rails_blob
        end
      route_for(route, blob)
    else
      # Use an environment variable instead of hard-coding the CDN host
      File.join(ENV.fetch("CDN_HOST"), blob.key)
    end
  end

  direct :cdn_image do |model, options|
    expires_in = options.delete(:expires_in) { ActiveStorage.urls_expire_in }
  
    if model.respond_to?(:signed_id)
      route_for(
        :rails_service_blob_proxy,
        model.signed_id(expires_in: expires_in),
        model.filename,
        options.merge(host: ENV['CDN_HOST'])
      )
    else
      signed_blob_id = model.blob.signed_id(expires_in: expires_in)
      variation_key  = model.variation.key
      filename       = model.blob.filename
  
      route_for(
        :rails_blob_representation_proxy,
        signed_blob_id,
        variation_key,
        filename,
        options.merge(host: ENV['CDN_HOST'])
      )
    end
  end

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  title      :string
#  content    :text
#  slug       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Article < ApplicationRecord
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  caption    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          not null
#
class Post < ApplicationRecord
  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [150, 150]
    attachable.variant :medium, resize_to_limit: [400, 400]
    attachable.variant :large, resize_to_limit: [900, 900]
  end
  
  belongs_to :user

  validates :caption, presence: true
  validates :image, presence: true

  scope :latest, -> { order(created_at: :desc) }

  def to_param
    "#{id}-#{caption.parameterize}"
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  first_name             :string
#  last_name              :string
#  username               :string
#  slug                   :string
#  bio                    :text
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :avatar
  has_many :posts, dependent: :destroy

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/cloudfrontable.rb
# app/controllers/concerns/cloudfrontable.rb
# frozen_string_literal: true

module Cloudfrontable
  extend ActiveSupport::Concern

  # Returns the Cloudfront URL for the given blob.
  def cloudfront_url(blob, options = {})
    uri = URI.parse("https://#{Rails.application.config.aws_cloudfront_domain}/#{blob.key}")
    query = [
      "response-content-type=#{URI.encode_www_form_component content_type(blob)}",
      "response-content-disposition=#{URI.encode_www_form_component(options[:disposition] || default_content_disposition(blob))}",
    ].compact.join('&')
    uri.query = query

    signer = Aws::CloudFront::UrlSigner.new(
      key_pair_id: Rails.application.config.aws_cloudfront_key_pair_id,
      private_key_path: Rails.application.config.aws_cloudfront_private_key_path,
    )

    signer.signed_url(
      uri.to_s,
      expires: Time.now.utc.to_i + ActiveStorage.service_urls_expire_in.to_i,
    )
  end

  private

  def default_content_disposition(blob)
    "inline; filename=\"#{filename(blob)}\"; filename*=UTF-8''#{filename(blob)}"
  end

  def amazon?
    Rails.application.config.active_storage.service == :amazon
  end

	# These two methods are needed in case you use variants. You'll need to make some changes
	# if you don't use variants with records.
  def content_type(blob)
    blob.is_a?(ActiveStorage::VariantWithRecord) ? blob.image.content_type : blob.content_type
  end

  def filename(blob)
    blob.is_a?(ActiveStorage::VariantWithRecord) ? blob.image.filename : blob.filename
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.latest
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save!
        format.html { redirect_to root_path, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, status: :see_other, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:caption, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Avogram" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script src="https://kit.fontawesome.com/079cca010f.js" crossorigin="anonymous"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
  </head>

  <body class="h-svh">
    <%= render "shared/sidebar" %>
    <main class="h-full mx-auto ml-[250px] pt-8 pb-16 px-5 flex">
      <%= yield %>
    </main>

    <div id="modal-container" data-controller="modal" class="fixed inset-0 z-50 overflow-y-auto hidden" aria-labelledby="modal-title" role="dialog" aria-modal="true">
      <div data-modal-target="backdrop" class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity duration-300 ease-out opacity-0"></div>
      <%= turbo_frame_tag "modal_content" %>
    </div>
  </body>
</html>

app/views/posts/_empty_state.html.erb
<div class="w-full h-full flex flex-col justify-start items-center mt-12">
  <%= image_tag "empty-state.svg", class: "mb-6" %>
  <div class="flex flex-col items-center max-w-1/2">
    <h4 class="text-xl font-medium">Your feed is empty!</h4>
    <p class="text-sm text-gray-500">Start following your friends to see their updates and content</p>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, class: "contents") do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="my-5">
    <%= form.label :image %>
    <%= form.file_field :image, class: "block mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :caption %>
    <%= form.text_field :caption, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>


  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<li id="<%= dom_id post %>" class="py-5 relative z-0">
  <div class="flex items-center space-x-2 mb-2">
    <div class="w-6 h-6 flex-shrink-0 rounded-full overflow-hidden">
      <%= image_tag "https://unavatar.io/github/erozas" %>
    </div>
    <div class="flex items-center space-x-3">
      <span class="font-semibold text-sm text-gray-900"><%= post.user.username %></span>
      <span class="text-xs text-gray-400"><%= time_ago_in_words(post.created_at) %> ago</span>
    </div>
  </div>
  <div class="aspect-square bg-gray-100 relative overflow-hidden rounded-md border border-gray-300 z-0">
    <%= image_tag cdn_image_url(post.image), class: "w-full h-full object-cover" %>
  </div>
  <div class="flex items-center space-x-4 mt-3">
    <i class="far fa-heart text-xl"></i>
    <i class="far fa-comment text-xl"></i>
    <i class="far fa-bookmark text-xl"></i>
  </div>
  <p class="text-slate-700 text-sm mt-2">
    <span class="font-semibold text-black"><%= link_to post.user.username, post_path(post) %></span>
    <span><%= post.caption %></span>
  </p>
  <p class="text-sm cursor-pointer text-gray-400 mt-3">Leave a comment</p>
</li>

app/views/posts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing post</h1>

  <%= render "form", post: @post %>

  <%= link_to "Show this post", @post, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to posts", posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/posts/index.html.erb
<% content_for :title, "Posts" %>

<div class="w-full h-screen flex justify-center">
  <div id="posts" class="w-[620px] flex">
    <% if @posts.any? %>
      <ul class="divide-y divide-slate-300 mx-16">
        <% @posts.each do |post| %>
          <%= render post %>
        <% end %>
      </ul>
    <% else %>
      <%= render "empty_state" %>
    <% end %>
  </div>

  <div class="ml-32 w-[320px] mt-8">
    <% if user_signed_in? %>
      <div class="flex space-x-3">
        <div class="w-10 h-10 bg-gray-200 rounded-full overflow-hidden">
          <%= image_tag "https://unavatar.io/github/#{current_user.username}", class: "w-full h-full object-cover" %>
        </div>
        <div class="flex flex-col justify-center">
          <span class="text-sm font-medium leading-tight"><%= current_user.username %></span>
          <span class="text-sm text-gray-500 leading-tight"><%= current_user.full_name %></span>
        </div>
      </div>
    <% end %>

    <div class="mt-6">
      <h5 class="text-sm font-medium text-gray-500">Suggested for you</h5>
      <div class="space-y-4 mt-4">
        <div class="flex space-x-3">
          <div class="w-10 h-10 flex-shrink-0 bg-gray-200 rounded-full overflow-hidden">
            <%= image_tag "https://i.pravatar.cc/100?img=15", class: "w-full h-full object-cover" %>
          </div>
          <div class="flex w-full items-center justify-between">
            <div class="flex flex-col justify-center">
              <span class="font-medium text-sm leading-tight">thans</span>
              <span class="text-sm text-gray-500 leading-tight">Travis Hanselman</span>
            </div>
            <button class="text-sm text-blue-500  font-medium">Follow</button>
          </div>
        </div>
        <div class="flex space-x-3">
          <div class="w-10 h-10 flex-shrink-0 bg-gray-200 rounded-full overflow-hidden">
            <%= image_tag "https://i.pravatar.cc/100?img=21", class: "w-full h-full object-cover" %>
          </div>
          <div class="flex w-full items-center justify-between">
            <div class="flex flex-col justify-center">
              <span class="font-medium text-sm leading-tight">jmagicd</span>
              <span class="text-sm text-gray-500 leading-tight">Jenna Davis</span>
            </div>
            <button class="text-sm text-blue-500  font-medium">Follow</button>
          </div>
        </div>
        <div class="flex space-x-3">
          <div class="w-10 h-10 flex-shrink-0 bg-gray-200 rounded-full overflow-hidden">
            <%= image_tag "https://i.pravatar.cc/100?img=32", class: "w-full h-full object-cover" %>
          </div>
          <div class="flex w-full items-center justify-between">
            <div class="flex flex-col justify-center">
              <span class="font-medium text-sm leading-tight">slopemary</span>
              <span class="text-sm text-gray-500 leading-tight">Maria Lopez</span>
            </div>
            <button class="text-sm text-blue-500  font-medium">Follow</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= turbo_frame_tag "modal_content" do %>
  <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
    <div class="fixed inset-0 bg-slate-600 bg-opacity-75 transition-opacity" aria-hidden="true"></div>
    <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>
      <div class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-2xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full">
        <div class="bg-white px-6 pt-6 pb-8 sm:p-6 sm:pb-8">
          <i class="far fa-times text-gray-800 absolute right-3 top-2.5 cursor-pointer" data-action="click->modal#close"></i>
          <h3 class="text-lg font-medium leading-6 text-gray-900" id="modal-title">Create new post</h3>
          <p class="text-gray-500 text-sm">Add an image and a caption and share your story with the world</p>
          <%= form_with(model: @post, local: true, data: { turbo_frame: "_top" }) do |form| %>
            <div class="border-2 border-dashed cursor-pointer border-gray-300 px-4 py-2 rounded-lg my-3 flex flex-col justify-center" data-controller="dropzone" data-action="click->dropzone#openFileDialog">
              <div class="hidden" data-dropzone-target="preview">
                <div class="flex items-center space-x-2">
                  <img src="" alt="" class="w-12 h-12 rounded-lg shadow-md object-cover">
                  <p class="text-gray-600 text-sm mt-1" data-dropzone-target="fileInfo">Archivo.jpg - 1.2 MB</p>
                </div>
                <div class="w-full rounded-full bg-gray-200 h-1.5 mt-2 hidden" data-dropzone-target="progressContainer">
                  <div class="rounded-full bg-blue-600 h-full transition-[width] duration-200" data-dropzone-target="progressBar" style="width: 0%"></div>
                </div>
              </div>
              <div data-dropzone-target="cta" class="flex flex-col items-center justify-center">
                <i class="far fa-image fa-2x text-gray-300"></i>
                <p class="text-gray-400 text-sm mt-1">Click to upload or drag and drop</p>
              </div>
              <%= form.file_field :image, direct_upload: true, class: "hidden", data: {dropzone_target: "input"} %>
            </div>
            <%= form.text_area :caption, placeholder: "What's on your mind?", rows: 4, class: "placeholder:text-sm placeholder:text-gray-400 resize-none w-full border border-gray-300 rounded-md text-gray-700 outline-2 focus:ring-2 focus:border-transparent focus:ring-gray-400" %>
            <%= form.button "Create", type: :submit, class: "w-full cursor-pointer bg-emerald-600 disabled:opacity-50 disabled:cursor-not-allowed hover:bg-emerald-500 transition-colors duration-300 text-white py-2 rounded-md mt-4", data: {behavior: "file-submit"} %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @post %>

    <%= link_to "Edit this post", edit_post_path(@post), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to posts", posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this post", @post, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>

app/views/shared/_feed_following_recommendation.html.erb
<aside class="w-full">
  <div class="flex items-center justify-between">
    <h4 class="text-base font-bold text-gray-500">Suggestions for you</h4>
  </div>
</aside>

app/views/shared/_sidebar.html.erb
<nav class="h-full flex-shrink-0 fixed inset-0 border-r border-gray-300 w-[250px] px-2">
  <header class="py-10 px-4">
    <%= link_to image_tag("logo.svg", class: "w-3/4"), root_path %>
  </header>
  <ul class="space-y-2">
    <li class="flex items-center space-x-2 cursor-pointer hover:bg-gray-100 py-3 px-4 rounded-md">
      <%= link_to root_path do %>
        <i class="far fa-home text-lg w-6"></i>
        <span>Home</span>
      <% end %>
    </li>
    <li class="flex items-center space-x-2 cursor-pointer hover:bg-gray-100 py-3 px-4 rounded-md">
      <div class="far fa-search text-lg w-6"></div>
      <span>Search</span>
    </li>
    <li class="flex items-center space-x-2 cursor-pointer hover:bg-gray-100 py-3 px-4 rounded-md">
      <div class="far fa-compass text-lg w-6"></div>
      <span>Explore</span>
    </li>
    <li class="flex items-center space-x-2 cursor-pointer hover:bg-gray-100 py-3 px-4 rounded-md">
      <div class="far fa-camera-movie text-lg w-6"></div>
      <span>Reels</span>
    </li>
    <li class="flex items-center space-x-2 cursor-pointer hover:bg-gray-100 py-3 px-4 rounded-md">
      <div class="far fa-messages text-lg w-6"></div>
      <span>Messages</span>
    </li>
    <li class="flex items-center space-x-2 cursor-pointer hover:bg-gray-100 py-3 px-4 rounded-md">
      <div class="far fa-heart text-lg w-6"></div>
      <span>Notifications</span>
    </li>
    <li class="flex items-center space-x-2 cursor-pointer hover:bg-gray-100 py-3 px-4 rounded-md">
      <button data-controller="modal" data-action="click->modal#open" class="w-full space-x-2 flex justify-start items-center">
        <div class="far fa-square-plus text-lg w-6"></div>
        <span>Create</span>
      </button>
    </li>
    <li class="flex items-center space-x-2 cursor-pointer hover:bg-gray-100 py-3 px-4 rounded-md">
      <div class="far fa-user text-lg w-6"></div>
      <span>Profile</span>
    </li>
  </ul>
  <div class="w-full overflow-hidden pb-4">
    <ul class="absolute bottom-3 right-2 left-0 flex flex-col space-y-2 max-w-full">
      <li class="w-full flex items-center space-x-2 cursor-pointer hover:bg-gray-100 py-2 px-4 rounded-md">
        <div class="relative">
          <i class="fa-brands fa-threads text-lg w-6"></i>
          <span class="w-4 h-4 bg-red-500 text-white text-xs font-bold flex items-center justify-center rounded-full absolute -right-1 -top-1">9</span>
        </div>
        <span>Spaces</span>
      </li>
      <li class="w-full flex items-center space-x-2 cursor-pointer hover:bg-gray-100 py-2 px-4 rounded-md">
        <div class="fa-solid fa-bars text-lg w-6"></div>
        <span>More</span>
      </li>
      <% if user_signed_in? %>
        <li class="w-full flex items-center space-x-2 cursor-pointer hover:bg-gray-100 py-2 px-4 rounded-md">
          <%= button_to destroy_user_session_path, method: :delete, class: "w-full flex items-center space-x-2 cursor-pointer hover:bg-gray-100 rounded-md" do %>
            <div class="fa-solid fa-sign-out text-lg w-6"></div>
            <span>Sign out</span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_stories.html.erb
<section class="w-full flex justify-start flex-nowrap overflow-x-auto items-center space-x-4">
  <% 12.times do |index| %>
    <div class="flex-shrink-0 story-avatar p-0.5 w-[60px] h-[60px] flex items-center justify-center">    
      <img src="https://i.pravatar.cc/100?img=<%= index * 3 %>" alt="Profile Picture" class="border-[3px] border-white rounded-full w-full h-full object-center">
    </div>
  <% end %>
</section>